FROM python:3.13-alpine

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apk update && \
    apk add --no-cache \
    gettext \
    graphviz \
    graphviz-dev

COPY src/requirements.txt /app/src/requirements.txt
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r /app/src/requirements.txt

COPY . /app/

WORKDIR /app/src
RUN python manage.py collectstatic --noinput

EXPOSE 8000

WORKDIR /app

# CMD ["sh", "source load-scripts.sh && loadsrc/scripts/entry-point.sh"]