FROM python:3.13-alpine

WORKDIR /app

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Install system dependencies needed by your Python packages (e.g., for graphviz)
# Do NOT install services like redis-server here
RUN apk update && \
    apk add --no-cache \
        gettext \
        graphviz \
        graphviz-dev

# Install Python dependencies
COPY src/requirements.txt /app/src/requirements.txt
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r /app/src/requirements.txt

# Copy the rest of the application code
COPY . /app/

# Expose the port for your Django/FastAPI application
EXPOSE 8000

# The command to run your application
CMD ["sh", "entrypoint.sh"]